### ISSUE TITLE
Infinite Recipe Query Loop

### ISSUE THREAD

**Issue by lebedevy** [hatchways/team-ivory#10]
When I navigate to the feed page, my server gets stuck in an infinite query loop while fetching the recipes. The query is below

    GET /api/recipes 304 4.806 ms - -
    Executing (default): SELECT "id", "userId", "name", "image", "ingredients", "steps", "tags", 
    "createdAt", "updatedAt" FROM "recipes" AS "recipes";

Currently, my db does not contain any data for recipes (in case that's relevant)

**Comment by jerryhuang3** [comment]
So it seems to be an issue with the lifecycle of the Feed component.

There is a fetch function that has a setState at the end of it. This is what's causing the component to rerender and run the fetch function over and over again.

Since he's using the useState hook, I wrapped it in a useEffect (similar to componentDidMount) hook with an empty array as a callback so that the function only runs once.
